#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface:
  def save_file(self, session_key, article_id, filename):
    pass

  def download_file(self, article_id, file_id):
    pass

  def delete_file(self, session_key, article_id, file_id):
    pass


class Client(Iface):
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot != None:
      self._oprot = oprot
    self._seqid = 0

  def save_file(self, session_key, article_id, filename):
    self.send_save_file(session_key, article_id, filename)
    return self.recv_save_file()

  def send_save_file(self, session_key, article_id, filename):
    self._oprot.writeMessageBegin('save_file', TMessageType.CALL, self._seqid)
    args = save_file_args()
    args.session_key = session_key
    args.article_id = article_id
    args.filename = filename
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_save_file(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = save_file_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success != None:
      return result.success
    if result.invalid != None:
      raise result.invalid
    if result.ouch != None:
      raise result.ouch
    if result.not_logged_in != None:
      raise result.not_logged_in
    raise TApplicationException(TApplicationException.MISSING_RESULT, "save_file failed: unknown result");

  def download_file(self, article_id, file_id):
    self.send_download_file(article_id, file_id)
    return self.recv_download_file()

  def send_download_file(self, article_id, file_id):
    self._oprot.writeMessageBegin('download_file', TMessageType.CALL, self._seqid)
    args = download_file_args()
    args.article_id = article_id
    args.file_id = file_id
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_download_file(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = download_file_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success != None:
      return result.success
    if result.invalid != None:
      raise result.invalid
    if result.ouch != None:
      raise result.ouch
    if result.not_logged_in != None:
      raise result.not_logged_in
    raise TApplicationException(TApplicationException.MISSING_RESULT, "download_file failed: unknown result");

  def delete_file(self, session_key, article_id, file_id):
    self.send_delete_file(session_key, article_id, file_id)
    return self.recv_delete_file()

  def send_delete_file(self, session_key, article_id, file_id):
    self._oprot.writeMessageBegin('delete_file', TMessageType.CALL, self._seqid)
    args = delete_file_args()
    args.session_key = session_key
    args.article_id = article_id
    args.file_id = file_id
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_delete_file(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = delete_file_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success != None:
      return result.success
    if result.invalid != None:
      raise result.invalid
    if result.ouch != None:
      raise result.ouch
    if result.not_logged_in != None:
      raise result.not_logged_in
    raise TApplicationException(TApplicationException.MISSING_RESULT, "delete_file failed: unknown result");


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["save_file"] = Processor.process_save_file
    self._processMap["download_file"] = Processor.process_download_file
    self._processMap["delete_file"] = Processor.process_delete_file

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_save_file(self, seqid, iprot, oprot):
    args = save_file_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = save_file_result()
    try:
      result.success = self._handler.save_file(args.session_key, args.article_id, args.filename)
    except InvalidOperation, invalid:
      result.invalid = invalid
    except InternalError, ouch:
      result.ouch = ouch
    except NotLoggedIn, not_logged_in:
      result.not_logged_in = not_logged_in
    oprot.writeMessageBegin("save_file", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_download_file(self, seqid, iprot, oprot):
    args = download_file_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = download_file_result()
    try:
      result.success = self._handler.download_file(args.article_id, args.file_id)
    except InvalidOperation, invalid:
      result.invalid = invalid
    except InternalError, ouch:
      result.ouch = ouch
    except NotLoggedIn, not_logged_in:
      result.not_logged_in = not_logged_in
    oprot.writeMessageBegin("download_file", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_delete_file(self, seqid, iprot, oprot):
    args = delete_file_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = delete_file_result()
    try:
      result.success = self._handler.delete_file(args.session_key, args.article_id, args.file_id)
    except InvalidOperation, invalid:
      result.invalid = invalid
    except InternalError, ouch:
      result.ouch = ouch
    except NotLoggedIn, not_logged_in:
      result.not_logged_in = not_logged_in
    oprot.writeMessageBegin("delete_file", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class save_file_args(object):

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'session_key', None, None, ), # 1
    (2, TType.I32, 'article_id', None, None, ), # 2
    (3, TType.STRING, 'filename', None, None, ), # 3
  )

  def __init__(self, session_key=None, article_id=None, filename=None,):
    self.session_key = session_key
    self.article_id = article_id
    self.filename = filename

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.session_key = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.article_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.filename = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('save_file_args')
    if self.session_key != None:
      oprot.writeFieldBegin('session_key', TType.STRING, 1)
      oprot.writeString(self.session_key)
      oprot.writeFieldEnd()
    if self.article_id != None:
      oprot.writeFieldBegin('article_id', TType.I32, 2)
      oprot.writeI32(self.article_id)
      oprot.writeFieldEnd()
    if self.filename != None:
      oprot.writeFieldBegin('filename', TType.STRING, 3)
      oprot.writeString(self.filename)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class save_file_result(object):

  thrift_spec = (
    (0, TType.STRUCT, 'success', (FileInfo, FileInfo.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'invalid', (InvalidOperation, InvalidOperation.thrift_spec), None, ), # 1
    (2, TType.STRUCT, 'ouch', (InternalError, InternalError.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'not_logged_in', (NotLoggedIn, NotLoggedIn.thrift_spec), None, ), # 3
  )

  def __init__(self, success=None, invalid=None, ouch=None, not_logged_in=None,):
    self.success = success
    self.invalid = invalid
    self.ouch = ouch
    self.not_logged_in = not_logged_in

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = FileInfo()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.invalid = InvalidOperation()
          self.invalid.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.ouch = InternalError()
          self.ouch.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.not_logged_in = NotLoggedIn()
          self.not_logged_in.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('save_file_result')
    if self.success != None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.invalid != None:
      oprot.writeFieldBegin('invalid', TType.STRUCT, 1)
      self.invalid.write(oprot)
      oprot.writeFieldEnd()
    if self.ouch != None:
      oprot.writeFieldBegin('ouch', TType.STRUCT, 2)
      self.ouch.write(oprot)
      oprot.writeFieldEnd()
    if self.not_logged_in != None:
      oprot.writeFieldBegin('not_logged_in', TType.STRUCT, 3)
      self.not_logged_in.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class download_file_args(object):

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'article_id', None, None, ), # 1
    (2, TType.I32, 'file_id', None, None, ), # 2
  )

  def __init__(self, article_id=None, file_id=None,):
    self.article_id = article_id
    self.file_id = file_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.article_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.file_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('download_file_args')
    if self.article_id != None:
      oprot.writeFieldBegin('article_id', TType.I32, 1)
      oprot.writeI32(self.article_id)
      oprot.writeFieldEnd()
    if self.file_id != None:
      oprot.writeFieldBegin('file_id', TType.I32, 2)
      oprot.writeI32(self.file_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class download_file_result(object):

  thrift_spec = (
    (0, TType.STRUCT, 'success', (DownloadFileInfo, DownloadFileInfo.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'invalid', (InvalidOperation, InvalidOperation.thrift_spec), None, ), # 1
    (2, TType.STRUCT, 'ouch', (InternalError, InternalError.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'not_logged_in', (NotLoggedIn, NotLoggedIn.thrift_spec), None, ), # 3
  )

  def __init__(self, success=None, invalid=None, ouch=None, not_logged_in=None,):
    self.success = success
    self.invalid = invalid
    self.ouch = ouch
    self.not_logged_in = not_logged_in

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = DownloadFileInfo()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.invalid = InvalidOperation()
          self.invalid.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.ouch = InternalError()
          self.ouch.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.not_logged_in = NotLoggedIn()
          self.not_logged_in.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('download_file_result')
    if self.success != None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.invalid != None:
      oprot.writeFieldBegin('invalid', TType.STRUCT, 1)
      self.invalid.write(oprot)
      oprot.writeFieldEnd()
    if self.ouch != None:
      oprot.writeFieldBegin('ouch', TType.STRUCT, 2)
      self.ouch.write(oprot)
      oprot.writeFieldEnd()
    if self.not_logged_in != None:
      oprot.writeFieldBegin('not_logged_in', TType.STRUCT, 3)
      self.not_logged_in.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class delete_file_args(object):

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'session_key', None, None, ), # 1
    (2, TType.I32, 'article_id', None, None, ), # 2
    (3, TType.I32, 'file_id', None, None, ), # 3
  )

  def __init__(self, session_key=None, article_id=None, file_id=None,):
    self.session_key = session_key
    self.article_id = article_id
    self.file_id = file_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.session_key = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.article_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.file_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('delete_file_args')
    if self.session_key != None:
      oprot.writeFieldBegin('session_key', TType.STRING, 1)
      oprot.writeString(self.session_key)
      oprot.writeFieldEnd()
    if self.article_id != None:
      oprot.writeFieldBegin('article_id', TType.I32, 2)
      oprot.writeI32(self.article_id)
      oprot.writeFieldEnd()
    if self.file_id != None:
      oprot.writeFieldBegin('file_id', TType.I32, 3)
      oprot.writeI32(self.file_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class delete_file_result(object):

  thrift_spec = (
    (0, TType.STRUCT, 'success', (FileInfo, FileInfo.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'invalid', (InvalidOperation, InvalidOperation.thrift_spec), None, ), # 1
    (2, TType.STRUCT, 'ouch', (InternalError, InternalError.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'not_logged_in', (NotLoggedIn, NotLoggedIn.thrift_spec), None, ), # 3
  )

  def __init__(self, success=None, invalid=None, ouch=None, not_logged_in=None,):
    self.success = success
    self.invalid = invalid
    self.ouch = ouch
    self.not_logged_in = not_logged_in

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = FileInfo()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.invalid = InvalidOperation()
          self.invalid.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.ouch = InternalError()
          self.ouch.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.not_logged_in = NotLoggedIn()
          self.not_logged_in.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('delete_file_result')
    if self.success != None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.invalid != None:
      oprot.writeFieldBegin('invalid', TType.STRUCT, 1)
      self.invalid.write(oprot)
      oprot.writeFieldEnd()
    if self.ouch != None:
      oprot.writeFieldBegin('ouch', TType.STRUCT, 2)
      self.ouch.write(oprot)
      oprot.writeFieldEnd()
    if self.not_logged_in != None:
      oprot.writeFieldBegin('not_logged_in', TType.STRUCT, 3)
      self.not_logged_in.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)


